# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['ENABLE_PSDB'] ? 'myapp_production' : 'myapp_production_development' %>
  port: <%= ENV['ENABLE_PSDB'] ? 3305 : ENV.fetch("DB_PORT", 3306) %>

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: mysql2
  database: myapp_production
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  host: <%= ENV['PRODUCTION_DB_HOST'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

