# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['ENABLE_PSDB'] == 'true' ? 'myapp_production' : 'db/myapp_development.sqlite3' %>
  adapter: <%= ENV['ENABLE_PSDB'] == 'true' ? 'mysql2' : 'sqlite3' %>
  username: <%= ENV['ENABLE_PSDB'] == 'true' ? ENV['DEVELOPMENT_DB_USERNAME'] : nil %>
  host: <%= ENV['ENABLE_PSDB'] == 'true' ? ENV['DEVELOPMENT_DB_HOST'] : nil %>
  password: <%= ENV['ENABLE_PSDB'] == 'true' ? ENV['DEVELOPMENT_DB_PASSWORD'] : nil %>
  port: <%= ENV['ENABLE_PSDB'] == 'true' ? 3305 : nil %>
  ssl_mode: <%= ENV['ENABLE_PSDB'] == 'true' ? 'verify_identity' : nil %>
  sslca: <%= ENV['ENABLE_PSDB'] == 'true' ? '/etc/ssl/cert.pem' : nil %>

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: mysql2
  database: myapp_production
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  host: <%= ENV['PRODUCTION_DB_HOST'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
  ssl_mode: verify_identity
  sslca: "/etc/ssl/cert.pem"

